"""empty message

Revision ID: 559cbcd7a67a
Revises: c93e96c7e237
Create Date: 2020-12-08 21:28:07.474685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559cbcd7a67a'
down_revision = 'c93e96c7e237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residents', sa.Column('transferSatisfiedMonth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residents', 'transferSatisfiedMonth')
    # ### end Alembic commands ###
