"""empty message

Revision ID: 6c6d4def3e63
Revises: 559cbcd7a67a
Create Date: 2020-12-14 11:23:43.692981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6d4def3e63'
down_revision = '559cbcd7a67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('delete', sa.Boolean(), nullable=True))
    op.add_column('residents', sa.Column('delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residents', 'delete')
    op.drop_column('apartment', 'delete')
    # ### end Alembic commands ###
