"""empty message

Revision ID: c93e96c7e237
Revises: 
Create Date: 2020-12-07 23:00:51.008615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93e96c7e237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('transferAmount', sa.Integer(), nullable=True),
    sa.Column('guaranteeCompany', sa.String(), nullable=True),
    sa.Column('roomNo', sa.String(), nullable=True),
    sa.Column('parkingLotNo', sa.String(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullName')
    )
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billingDate', sa.Date(), nullable=False),
    sa.Column('residents_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['residents_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferDate', sa.Date(), nullable=False),
    sa.Column('transferAmount', sa.Integer(), nullable=False),
    sa.Column('residents_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['residents_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('billing')
    op.drop_table('residents')
    op.drop_table('apartment')
    # ### end Alembic commands ###
